### ISSUE TITLE
get quotes library json error

### ISSUE THREAD

**Issue by pushand** [zerodhatech/gokiteconnect#13]
when i try following I get below response for most of the quotes

quotes, err := s.kiteClient.GetQuote(symbols...)
response: 
Error parsing JSON response: invalid character '<' looking for beginning of value

symbols are in format 'NSE:ADANIPOWER' so on...

**Comment by vividvilla** [comment]
Is this issue reproducible always? I tried running a test script and I was able to retrieve data.

**Comment by vividvilla** [comment]
Is this issue reproducible always? I tried running a test script and I was able to retrieve data.

**Comment by pushand** [comment]
I queried 3times for 1k, 1k and 500 symbols of NSE and for all 3 I got above error for many stocks while others were parsed successfully

**Comment by pushand** [comment]
It seems that querying about 500 stocks instead of 1000 at a time doesn't give the above trace. closing it.
