### ISSUE TITLE
ticker Order update not called

### ISSUE THREAD

**Issue by pushand** [zerodhatech/gokiteconnect#17]
ticker.OnOrderUpdate fails to unmarshal order JSON

logs

message type 1

message:  {order map[account_id:REMOVED app_id:00000 average_price:0 cancelled_quantity:0 checksum: disclosed_quantity:0 exchange:NSE exchange_order_id:<nil> exchange_timestamp:<nil> exchange_update_timestamp:<nil> filled_quantity:0 guid:10982Xg2D0yM5lJyIG instrument_token:41729 market_protection:0 meta:map[] meta_raw:<nil> order_id:200106003187256 order_timestamp:2020-01-06 17:34:22 order_type:LIMIT parent_order_id:<nil> pending_quantity:0 placed_by:KITEID price:160.65 product:BO quantity:1 status:REJECTED status_message:BO: auto square off executed status_message_raw:BO: auto square off executed tag:bs tags:[bs] tradingsymbol:APOLLOTYRE transaction_type:BUY trigger_price:0 unfilled_quantity:0 validity:DAY variety:bo]}

error parsing order json: cannot unmarshal object into Go struct field Order.data.meta of type string

error code: zerodhatech/gokiteconnect/ticker/ticker.go 
error line: 604 if err := json.Unmarshal(inp, &order); err != nil {}

it was working good previous version. request for hot fix. thanks

**Comment by rhnvrm** [comment]
Can you please share the version you are using?

We had pushed a fix in v3.0.1 and it should also be available in v3.1.0

**Comment by pushand** [comment]
updated and working. thanks
