### ISSUE TITLE
Websocket: bad handshake

### ISSUE THREAD

**Issue by PawanWagh** [zerodhatech/gokiteconnect#9]
I've used example code provided in your SDK and replaced `api_key` & `access_key` with proper credentials. Nodejs SDK is working as expected. 
I'm getting this error - 
```
Error:  websocket: bad handshake
Reconnect attempt 1 in 2.000000s
Error:  websocket: bad handshake
Reconnect attempt 2 in 4.000000s
Error:  websocket: bad handshake
Reconnect attempt 3 in 8.000000s
Error:  websocket: bad handshake
Reconnect attempt 4 in 16.000000s
Error:  websocket: bad handshake
Reconnect attempt 5 in 32.000000s
Error:  websocket: bad handshake
Reconnect attempt 6 in 60.000000s
Error:  websocket: bad handshake
Reconnect attempt 7 in 60.000000s
Error:  websocket: bad handshake
Reconnect attempt 8 in 60.000000s
Error:  websocket: bad handshake
Reconnect attempt 9 in 60.000000s
Error:  dial tcp: lookup ws.kite.trade: no such host
```

**Comment by rhnvrm** [comment]
@PawanWagh - The example code was working before #11 for both `ticker.go` and `connect.go` but I added more details in `ticker.go` in #11.

I suspect that most likely the keys were given incorrectly by you so it would have given a bad handshake error. Please try again, and share the code you compiled here in case it still does not work for you.

**Comment by vividvilla** [comment]
Closing the issue because of non activity. Feel free to reopen it if required.
